### ISSUE TITLE
ios: video is not present on Preferences Test

### ISSUE THREAD

**Issue by dhreben** [zebrunner/appium#199]
Log:

```
/ed004511-b33f-441c-9854-bfd92a4aae2f': File exists
[info] [CaptureArtifacts] generating video file 40a10047-1bd0-4f80-8aba-5bd41371682f.mp4...
waiting for Appium start...
```

**Comment by vdelendik** [comment]
fixed by adding one more condition to detect finishSessionId: https://github.com/zebrunner/appium/commit/fbc368bc5f9e28a8b6c193693c2957abee8fefaa#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R205

earlier based on the pattern we detected asap secondary message for previous session and stop recording. rebuilt appium:2.0, restarting...

**Comment by dhreben** [comment]
Fixed
